name: Build and deploy Spring-boot app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy a demo spring boot project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file demo-project-for-github-actions/pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file demo-project-for-github-actions/pom.xml
